// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParrotsApplication.Data;

namespace ParrotsApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParrotsApplication.Models.Parrot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NoiseLevel")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Parrots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Djaro",
                            NoiseLevel = 3.0,
                            Size = "Large",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hamlet",
                            NoiseLevel = 4.5,
                            Size = "Medium",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gizmo",
                            NoiseLevel = 3.0,
                            Size = "Large",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kiwi",
                            NoiseLevel = 4.0,
                            Size = "Medium",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "YumYum",
                            NoiseLevel = 3.0,
                            Size = "Small",
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ginger",
                            NoiseLevel = 3.0,
                            Size = "Small",
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Apollo",
                            NoiseLevel = 3.0,
                            Size = "Large",
                            SpeciesId = 1
                        });
                });

            modelBuilder.Entity("ParrotsApplication.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "African Gray"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Indian Blue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cockatiel"
                        });
                });

            modelBuilder.Entity("ParrotsApplication.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParrotId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParrotId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParrotId = 3,
                            Value = "https://www.youtube.com/shorts/YCVK-aqeAHo"
                        },
                        new
                        {
                            Id = 2,
                            ParrotId = 3,
                            Value = "https://www.youtube.com/shorts/QrmWkpblL_U"
                        },
                        new
                        {
                            Id = 3,
                            ParrotId = 2,
                            Value = "https://www.youtube.com/shorts/1rLyvVi8nRU"
                        },
                        new
                        {
                            Id = 4,
                            ParrotId = 2,
                            Value = "https://www.youtube.com/shorts/EA9J3poFlOs"
                        },
                        new
                        {
                            Id = 5,
                            ParrotId = 5,
                            Value = "https://www.youtube.com/shorts/UFt2pt7eTyY"
                        },
                        new
                        {
                            Id = 6,
                            ParrotId = 4,
                            Value = "https://www.youtube.com/shorts/Hw8-jbTtqdA"
                        },
                        new
                        {
                            Id = 7,
                            ParrotId = 1,
                            Value = "https://www.youtube.com/watch?v=er9uysEEyX4"
                        },
                        new
                        {
                            Id = 8,
                            ParrotId = 1,
                            Value = "https://www.youtube.com/watch?v=7Arab-zmne0"
                        },
                        new
                        {
                            Id = 9,
                            ParrotId = 6,
                            Value = "https://www.youtube.com/watch?v=MIAwx3XwnsY"
                        },
                        new
                        {
                            Id = 10,
                            ParrotId = 7,
                            Value = "https://www.youtube.com/shorts/_AmBMMv88rI"
                        },
                        new
                        {
                            Id = 11,
                            ParrotId = 7,
                            Value = "https://www.youtube.com/shorts/FVxlikv7QWM"
                        },
                        new
                        {
                            Id = 12,
                            ParrotId = 7,
                            Value = "https://www.youtube.com/shorts/RrM9DmeevAA"
                        });
                });

            modelBuilder.Entity("ParrotsApplication.Models.Parrot", b =>
                {
                    b.HasOne("ParrotsApplication.Models.Species", "Species")
                        .WithMany("Parrots")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ParrotsApplication.Models.Video", b =>
                {
                    b.HasOne("ParrotsApplication.Models.Parrot", "Parrot")
                        .WithMany("Videos")
                        .HasForeignKey("ParrotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parrot");
                });

            modelBuilder.Entity("ParrotsApplication.Models.Parrot", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ParrotsApplication.Models.Species", b =>
                {
                    b.Navigation("Parrots");
                });
#pragma warning restore 612, 618
        }
    }
}
